### ISSUE TITLE
License missing.

### ISSUE THREAD

**Issue by athanasiosem** [skuarch/HibernateGenericDaoFind#1]
Hello. 

Under what license is this code licensed?
I cannot find any license file in your code.
Please let me know.

Thank you in advance.

**Comment by skuarch** [comment]
GPL or open source if you need something just take it

**Comment by athanasiosem** [comment]
Please include a LICENSE file stating clearly the LICENSE the project uses so I can download it. http://choosealicense.com/ can help you with open source licenses.

**Comment by skuarch** [comment]
now the project is under GPL v2
